AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - "db/**/*.sqlite3"
    - "node_modules/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "db/migrations/*.rb"

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/AbcSize:
  Exclude:
    - "test/**/*_test.rb"

Metrics/ClassLength:
  Exclude:
    - "test/**/*_test.rb"
    - "lib/sla/status_page.rb"
    - "lib/sla/github_client.rb"
    - "lib/sla/tracker.rb"

Metrics/MethodLength:
  Exclude:
    - "test/**/*_test.rb"

Layout/ClassStructure:
  Enabled: true
